# Generated by Django 5.2.7 on 2026-01-16 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_email', models.EmailField(max_length=254)),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('completed', 'Completed Job'), ('rewarded', 'Reward Given')], default='pending', max_length=20)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages_received', models.PositiveIntegerField(default=0)),
                ('total_response_time_seconds', models.BigIntegerField(default=0)),
                ('average_response_time_seconds', models.PositiveIntegerField(default=0)),
                ('total_proposals_received', models.PositiveIntegerField(default=0)),
                ('total_proposal_response_time_seconds', models.BigIntegerField(default=0)),
                ('average_proposal_response_time_seconds', models.PositiveIntegerField(default=0)),
                ('jobs_completed', models.PositiveIntegerField(default=0)),
                ('jobs_on_time', models.PositiveIntegerField(default=0)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('last_message_sent', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
    ]
