# Generated by Django 5.2.4 on 2025-08-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=255, verbose_name='username'),
            preserve_default=False,
        ),
    ]
