# Generated by Django 5.2.4 on 2025-09-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('GH', 'Ghana'), ('NG', 'Nigeria')], default='GH', max_length=2),
        ),
    ]
