# Generated by Django 5.2.4 on 2025-07-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
