# Generated by Django 5.2.4 on 2025-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_open',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_REVIEW', 'Awaiting Review'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='System Notification', max_length=255),
        ),
    ]
