# Generated by Django 5.2.4 on 2025-07-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='job_app_attachments/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20),
        ),
    ]
