# Generated by Django 5.2.4 on 2025-08-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
