# Generated by Django 5.2.4 on 2025-08-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_skill_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='approved',
        ),
    ]
