# Generated by Django 5.2.4 on 2025-08-20 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_skill_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='freelancer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_freelancer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
