# Generated by Django 5.2.4 on 2025-08-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='approved',
        ),
    ]
