# Generated by Django 5.2.7 on 2026-01-16 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_skill_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('writing', 'Writing'), ('marketing', 'Marketing'), ('video', 'Video & Animation'), ('music', 'Music & Audio'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon class name (e.g., 'fa-python')", max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Featured in popular skills list'),
        ),
        migrations.CreateModel(
            name='SkillBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('name', models.CharField(help_text="e.g., 'Certified Python Developer'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_color', models.CharField(default='#4CAF50', help_text='Badge color (hex)', max_length=20)),
                ('verification_method', models.CharField(choices=[('test', 'Online Test'), ('portfolio', 'Portfolio Review'), ('work_history', 'Work History'), ('certificate', 'External Certificate'), ('admin', 'Admin Verified')], default='test', max_length=20)),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum % to pass (for tests)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='jobs.skill')),
            ],
            options={
                'ordering': ['skill__name', 'level'],
                'unique_together': {('skill', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserSkillBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Test score if applicable', null=True)),
                ('certificate_url', models.URLField(blank=True, help_text='Link to external certificate', null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='jobs.skillbadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_badges', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
