# Generated by Django 5.2.7 on 2026-01-16 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_skill_category_skill_description_skill_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='job_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['client', 'status'], name='job_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['freelancer', 'status'], name='job_freelancer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['budget'], name='job_budget_idx'),
        ),
    ]
