# Generated by Django 5.2.7 on 2026-01-16 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0006_remove_contract_end_date_contract_complete_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('quality', 'Quality of Work'), ('deadline', 'Missed Deadline'), ('payment', 'Payment Issue'), ('communication', 'Communication Problems'), ('scope', 'Scope Disagreement'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the dispute')),
                ('evidence', models.FileField(blank=True, help_text='Supporting documents or screenshots', null=True, upload_to='disputes/evidence/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_client', 'Resolved in Favor of Client'), ('resolved_freelancer', 'Resolved in Favor of Freelancer'), ('resolved_compromise', 'Resolved by Compromise'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the dispute was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contracts.contract')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='disputes/comments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_comments', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='disputes.dispute')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
