# Generated by Django 5.2.4 on 2025-08-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_agreed_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira'), ('KES', 'Kenyan Shilling')], default='USD', max_length=3),
        ),
    ]
