# Generated by Django 5.2.4 on 2025-08-25 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('contract_accepted', 'Contract Accepted'), ('payment_released', 'Payment Released'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved')], max_length=50),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
