# Generated by Django 5.2.4 on 2025-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_audittrail_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='pending_acceptance', max_length=20),
        ),
    ]
