# Generated by Django 5.2.4 on 2025-08-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.AddField(
            model_name='contract',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('active', 'Active'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='pending_acceptance', max_length=20),
        ),
    ]
