# Generated by Django 5.2.7 on 2026-01-16 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_remove_contract_end_date_contract_complete_and_more'),
        ('jobs', '0017_job_job_status_created_idx_job_job_client_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contract_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client', 'status'], name='contract_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['freelancer', 'status'], name='contract_freelancer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='contract_created_idx'),
        ),
    ]
