# Generated by Django 5.2.7 on 2026-01-16 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contract_options_contract_contract_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('design', 'Design'), ('writing', 'Content Writing'), ('marketing', 'Digital Marketing'), ('video', 'Video Production'), ('data', 'Data & Analytics'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('job_title_template', models.CharField(help_text="Template for job title, e.g., 'Build a {type} website'", max_length=200)),
                ('job_description_template', models.TextField(help_text='Template for job description with placeholders')),
                ('contract_terms_template', models.TextField(blank=True, help_text='Standard contract terms for this type of project')),
                ('suggested_budget_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_budget_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_duration_days', models.PositiveIntegerField(help_text='Typical duration in days')),
                ('milestones_template', models.JSONField(default=list, help_text='List of milestone templates [{title, description, percentage}]')),
                ('suggested_skills', models.JSONField(default=list, help_text='List of skill names typically required')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
    ]
