# Generated by Django 5.2.4 on 2025-08-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='cached_metrics',
            field=models.JSONField(blank=True, default=dict, help_text="Cached metrics (e.g., {'total_earnings': 5000, 'pending_transactions': 2, 'unread_messages': 1})"),
        ),
    ]
