# Generated by Django 5.2.4 on 2025-08-20 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0014_alter_job_freelancer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(limit_choices_to={'user_type': 'freelancer'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_sent', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_received', to='jobs.job')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('freelancer', 'job'), name='unique_proposal_per_job')],
            },
        ),
    ]
