# Generated by Django 5.2.7 on 2025-10-10 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_currency_escrowaccount_transaction_withdrawal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowaccount',
            name='user',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_account', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
